version: "2.3"
services:
  emby:
    image: emby/embyserver:beta
    container_name: embyserver
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100,44,122 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /mnt/docker/emby/config:/config
      - /mnt/9C33-6BBD/Media/Shows:/tv
      - /mnt/9C33-6BBD/Media/Movies:/movies
      - /mnt/9C33-6BBD/Media/downloads:/other
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    restart: always
